trigger:
  - master

pr:
  autoCancel: true
  branches:
    include:
      - "*"

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

jobs:
  - job: e2e
    displayName: End-to-End Tests
    # re-enable once we upgrade our subscription to cypress
    # strategy:
    #   parallel: 4
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: UseDotNet@2
        inputs:
          version: '3.1.x'
          packageType: runtime
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          projects: BotProject/Templates/CSharp
      - task: NodeTool@0
        displayName: "Use Node 12.13.0"
        inputs:
          versionSpec: 12.13.0
      - task: CacheBeta@1
        inputs:
          key: yarn | $(Agent.OS) | Composer/yarn.lock
          path: $(YARN_CACHE_FOLDER)
          restoreKeys: |
            yarn | $(Agent.OS)
        displayName: Cache Yarn packages
      - task: CacheBeta@1
        displayName: Cache Cypress binary
        inputs:
          key: cypress | $(Agent.OS) | Composer/yarn.lock
          path: /home/vsts/.cache/Cypress
      - script: yarn --frozen-lock-file
        displayName: yarn install
        workingDirectory: Composer
      - script: yarn build
        displayName: yarn build
        workingDirectory: Composer
      - task: PublishPipelineArtifact@1
        displayName: Publish Cypress Artifacts
        condition: failed()
        continueOnError: true
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)/cypress
          artifactName: e2e
      - script: cat e2e.log
        displayName: Server Logs
        condition: always()
        continueOnError: true
        workingDirectory: Composer
      - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
        displayName: 'Component Detection'






